# -*- coding: utf-8 -*-
"""WordCount-Spark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ShT5hz94Dq4m3SibaTIIqS5CjZwjQekq
"""

import sys

!pip install pyspark

from pyspark import SparkContext

sc = SparkContext("local", "WordCount", 'biblia', None)

lines = sc.textFile('biblia.txt')

counts = lines.flatMap(lambda s: s.split(" ")).map(lambda word: (word, 1)).reduceByKey(lambda x, y: x + y)

counts.saveAsTextFile('saida.txt')